webtalk_init -webtalk_dir C:/Users/krystufek/Desktop/PS/PS.sim/sim_1/behav/xsim/xsim.dir/tb_urm_driver_decoder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  1 13:37:55 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "59eb6311-6cee-458f-ad10-62aebf2aca88" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ca2f7cd4e7fb42ea9f04f1a5f5ac0ac5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "50 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.53_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14320_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1004683788 -regid "" -xml C:/Users/krystufek/Desktop/PS/PS.sim/sim_1/behav/xsim/xsim.dir/tb_urm_driver_decoder_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/krystufek/Desktop/PS/PS.sim/sim_1/behav/xsim/xsim.dir/tb_urm_driver_decoder_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/krystufek/Desktop/PS/PS.sim/sim_1/behav/xsim/xsim.dir/tb_urm_driver_decoder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
